### ISSUE TITLE
Port forwarding broken when SFE enabled on latest AUG build

### ISSUE THREAD

**Issue by Patazerty** [gwlim/openwrt-sfe-flowoffload#61] opened 2019-08-07 10:01 UTC
After updating from the previous AUG build to the current one on my archer C7, I noticed port forwarding was breaking as soon as SFE kicks in (after 4 packets). Using netcat to debug, the connection would establish and a few packets can arrive, but then when SFE picks up the connection, nothing would arrive until one side closes the connection. Reverting to the previous AUG build and port forwarding is working fine again (but no ipv6 accelerated with SFE).

**Comment by gwlim** [comment] 2019-08-07 13:22
I am able to setup a local port forwarding setup both TCP and UDP using JPerf, you have to give me more details for this.

**Comment by gwlim** [comment] 2019-08-08 11:47
I tested port forward on my WAN link, no problem reaching the internal ip & port as far as I can tell.
I will close this ticket until more information is given

**Closed by gwlim** 2019-08-08 11:47 UTC

**Comment by Xmister** [comment] 2019-08-09 14:54
I have the same issue (Archer C7 v4), although my case a little bit special:
I have another router behind my openwrt router that is also doing NAT.
Reaching internet behind the second router works fine, but if I forward a port from the sfe router to the second router it's like the MSS Clamping rule wouldn't work, as in small packets get through the connection but bigger ones are getting dropped and retransmitted. (I'm using PPoE)

**Comment by Patazerty** [comment] 2019-08-09 15:05
I can only access the router remotely for now, will do more testing in a few days

**Comment by gwlim** [comment] 2019-08-11 01:19
> @gwlim
> I have the same issue (Archer C7 v4), although my case a little bit special:
> I have another router behind my openwrt router that is also doing NAT.
> Reaching internet behind the second router works fine, but if I forward a port from the sfe router to the second router it's like the MSS Clamping rule wouldn't work, as in small packets get through the connection but bigger ones are getting dropped and retransmitted. (I'm using PPoE)

Try setting MTU = 1492?

**Comment by Xmister** [comment] 2019-08-11 20:39
> > @gwlim
> > I have the same issue (Archer C7 v4), although my case a little bit special:
> > I have another router behind my openwrt router that is also doing NAT.
> > Reaching internet behind the second router works fine, but if I forward a port from the sfe router to the second router it's like the MSS Clamping rule wouldn't work, as in small packets get through the connection but bigger ones are getting dropped and retransmitted. (I'm using PPoE)
> 
> Try setting MTU = 1492?

I've tried that before, but didn't help. I'm not sure if the MSS is the actual issue, it just has very similar symptoms: Small packages go through, big ones don't. Like HTTP works, but HTTPS doesn't, because of the larger SSL packets.

**Comment by gwlim** [comment] 2019-08-12 11:38
> > > @gwlim
> > > I have the same issue (Archer C7 v4), although my case a little bit special:
> > > I have another router behind my openwrt router that is also doing NAT.
> > > Reaching internet behind the second router works fine, but if I forward a port from the sfe router to the second router it's like the MSS Clamping rule wouldn't work, as in small packets get through the connection but bigger ones are getting dropped and retransmitted. (I'm using PPoE)
> > 
> > 
> > Try setting MTU = 1492?
> 
> I've tried that before, but didn't help. I'm not sure if the MSS is the actual issue, it just has very similar symptoms: Small packages go through, big ones don't. Like HTTP works, but HTTPS doesn't, because of the larger SSL packets.

Nope SSL Packets sizes are the same. 
I just tested port forward external port 6001 to second AP on https port 443.
Works fine.

**Comment by Xmister** [comment] 2019-08-12 13:17
Well, SSL packets usually have the DF bit set, so they tend to arrive in bigger chunks.
Anyway, what kind of log/test would you need to help in debugging?

**Comment by gwlim** [comment] 2019-08-12 13:53
I just need a reliable way to reproduce this.
A simple test case that demonstrate this

**Comment by Xmister** [comment] 2019-08-12 14:01
This is the route of the connection:

```
Incoming SSH      Port Forward to 10.0.1.2     Port Forward to 10.0.3.10
     PPPOE WAN ----------> SFE Router ------------------> Other router ------------------> Destination
                       <wan ip> / 10.0.1.1            10.0.1.2 / 10.0.3.3                    10.0.3.10
```
The ports are always 22.

**Comment by gwlim** [comment] 2019-08-13 15:13
Update: 
I am able to reproduce the issue, and the issue has to do with which route SFE chooses first.
The fix seems to work, right now I am running it on my main router to see if there is any issues.
Will probably be in the next release if there are no issues.

**Comment by Xmister** [comment] 2019-08-13 15:14
Great news, thank you!

**Comment by 0sy** [comment] 2019-08-14 16:09
Hi gwlim - thank you so much for your work. Same issue here, on Tp-Link WR-1043ND v2.

Quick question here to you and the others experiencing it - would disabling SFE allow port forwarding to function as intended? CC @Patazerty @Xmister @gwlim

**Comment by Xmister** [comment] 2019-08-14 19:51
@0sy Yes, disabling SFE solves the issue for me.

**Comment by Zsolteeca** [comment] 2019-08-15 17:42
> 
> 
> Update:
> I am able to reproduce the issue, and the issue has to do with which route SFE chooses first.
> The fix seems to work, right now I am running it on my main router to see if there is any issues.
> Will probably be in the next release if there are no issues.

When will be the next release?

**Comment by Zsolteeca** [comment] 2019-08-18 19:23
I am looking forward to the new version of your firmware

**Comment by Xmister** [comment] 2019-08-28 09:05
Works fine after the SEP update, thank you!
